mode = "light"

accent = "#865951"
selection = "#c4bfae"
muted = "#84827c"

background = "#F8F1D6"
dark_background = "#bab5a0"
darker_background = "#7c786b"
lighter_background = "#f9f2da"

foreground = "#272B29"
dark_foreground = "#1d201e"
light_foreground = "#474b49"
bright_foreground = "#5d605e"

red = "#694b31"
yellow = "#1b0400"
orange = "#4e3220"
green = "#3a2a00"
cyan = "#231b00"
blue = "#865951"
magenta = "#5e301a"
brown = "#2b1c12"

bright_red = "#593614"
bright_yellow = "#260700"
bright_green = "#2b1700"
bright_cyan = "#1b1000"
bright_blue = "#764239"
bright_magenta = "#501800"
